import { Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({ weight: ['100', '400', '700', '900'], subsets: ['latin'] }); // Add Outfit with desired weights



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>{children}</body>
    </html>
  );
}
